shfmt

diff --git a/default/bin/git-tmp b/default/bin/git-tmp
--- a/default/bin/git-tmp
+++ b/default/bin/git-tmp
@@ -10,36 +10,36 @@ escape() {
 }
 
 case "$ACTION" in
-  init)
-    if git rev-parse --is-inside-work-tree &> /dev/null; then
-      echo 'Error: already in a git work tree' >&2
-      exit 1
-    fi
+init)
+  if git rev-parse --is-inside-work-tree &>/dev/null; then
+    echo 'Error: already in a git work tree' >&2
+    exit 1
+  fi
 
-    git init --separate-git-dir "$TMPDIR/$(pwd | escape).git" > /dev/null
-    git config user.email 'tmp@localhost' > /dev/null
-    git add --all > /dev/null
-    git commit -n -m 'initial commit' > /dev/null
-    git status
-    ;;
-  done)
-    GIT_DIR="$(git rev-parse --git-dir)"
-    TMP_GIT_DIR="$TMPDIR/$(git rev-parse --show-toplevel | escape).git"
+  git init --separate-git-dir "$TMPDIR/$(pwd | escape).git" >/dev/null
+  git config user.email 'tmp@localhost' >/dev/null
+  git add --all >/dev/null
+  git commit -n -m 'initial commit' >/dev/null
+  git status
+  ;;
+done)
+  GIT_DIR="$(git rev-parse --git-dir)"
+  TMP_GIT_DIR="$TMPDIR/$(git rev-parse --show-toplevel | escape).git"
 
-    if ! [ "${GIT_DIR#/private}" = "${TMP_GIT_DIR#/private}" ]; then
-      echo 'Error: this repo is not created by git tmp' >&2
-      echo "Expected: ${TMP_GIT_DIR}" >&2
-      echo "Real:     ${GIT_DIR}" >&2
-      exit 1
-    fi
+  if ! [ "${GIT_DIR#/private}" = "${TMP_GIT_DIR#/private}" ]; then
+    echo 'Error: this repo is not created by git tmp' >&2
+    echo "Expected: ${TMP_GIT_DIR}" >&2
+    echo "Real:     ${GIT_DIR}" >&2
+    exit 1
+  fi
 
-    DOT_GIT_FILE="$(git rev-parse --show-toplevel)/.git"
-    echo "rm -f '$DOT_GIT_FILE'"
-    rm -f "$DOT_GIT_FILE"
-    echo "rm -rf '$GIT_DIR'"
-    rm -rf "$GIT_DIR"
-    ;;
-  *)
-    echo "ckb tmp init|done"
-    ;;
+  DOT_GIT_FILE="$(git rev-parse --show-toplevel)/.git"
+  echo "rm -f '$DOT_GIT_FILE'"
+  rm -f "$DOT_GIT_FILE"
+  echo "rm -rf '$GIT_DIR'"
+  rm -rf "$GIT_DIR"
+  ;;
+*)
+  echo "ckb tmp init|done"
+  ;;
 esac
diff --git a/default/bin/netselect b/default/bin/netselect
--- a/default/bin/netselect
+++ b/default/bin/netselect
@@ -10,26 +10,27 @@
 # cmdline options:
 while getopts ":qv" opt; do
   case $opt in
-      q) exec 2>/dev/null ;; # quiet mode; only outputs fastest server.
-      v) verbose=1 ;;        # full output.
-      *) echo >&2 "ERROR: CMDLINE opts allowed are -q or -v" && exit 1;;
+  q) exec 2>/dev/null ;; # quiet mode; only outputs fastest server.
+  v) verbose=1 ;;        # full output.
+  *) echo >&2 "ERROR: CMDLINE opts allowed are -q or -v" && exit 1 ;;
   esac
 done
 
 # sorting
-PING_atempts=5 # change 
+PING_atempts=5 # change
 echo >&2 "Be patient, this might take a while..."
-LIST="$(while read mirror; do echo >&2 "Testing \"$mirror\"";
-    speed="$(command ping -q -c $PING_atempts $mirror 2>&1 |\
-    awk -F '/' '{if(/^(round-trip|rtt) /){print $5}}')" # rtts avg 
-    printf "%-25s ----> %s\n" $mirror $speed; done;)"
+LIST="$(while read mirror; do
+  echo >&2 "Testing \"$mirror\""
+  speed="$(command ping -q -c $PING_atempts $mirror 2>&1 |
+    awk -F '/' '{if(/^(round-trip|rtt) /){print $5}}')" # rtts avg
+  printf "%-25s ----> %s\n" $mirror $speed
+done)"
 SORTED_LIST=$(echo "$LIST" | sort -n -k 3)
 
 # output
 if [ "$verbose" == "1" ]; then
-    echo >&2 "Sorting results, time is in ms:"
-    echo "${SORTED_LIST}"
+  echo >&2 "Sorting results, time is in ms:"
+  echo "${SORTED_LIST}"
 else
-    echo "${SORTED_LIST}" | sed -n "1s/ .*//p"
+  echo "${SORTED_LIST}" | sed -n "1s/ .*//p"
 fi
-
